CREATE TABLE MEMBER (
    ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255),
    AGE INTEGER,
    PRIMARY KEY (ID)
);

CREATE TABLE HW_MEMBER (
    ID BIGINT NOT NULL,
    NAME VARCHAR(255),
    PRIMARY KEY (ID)
);
