Hibernate:
drop table if exists member cascade
    Hibernate:
drop table if exists team cascade
    Hibernate:
drop table if exists team_member cascade
    Hibernate:
create table member (
                        id bigint generated by default as identity,
                        name varchar(50) not null,
                        primary key (id)
)
    Hibernate:
create table team (
                      id bigint generated by default as identity,
                      name varchar(255),
                      primary key (id)
)
    Hibernate:
create table team_member (
                             members_id bigint not null unique,
                             team_id bigint not null
)
    Hibernate:
alter table if exists team_member
    add constraint FK7cy1n8pa4ielhb75i4pymy4ry
    foreign key (members_id)
    references member
    Hibernate:
alter table if exists team_member
    add constraint FK9ubp79ei4tv4crd0r9n7u5i6e
    foreign key (team_id)
    references team
    Hibernate:
    /* insert
    for
        chapter6.homework1.Team
        */insert
    into
    team (name, id)
    values
    (?, default)
    Hibernate:
    /* insert
    for
        chapter6.homework1.Member
        */insert
    into
    member (name, id)
    values
    (?, default)
    Hibernate:
    /* insert
    for
        chapter6.homework1.Member
        */insert
    into
    member (name, id)
    values
    (?, default)
    Hibernate:
    /* insert
    for
        chapter6.homework1.Team.members
        */insert
    into
    team_member (team_id, members_id)
    values
    (?, ?)
    Hibernate:
    /* insert
    for
        chapter6.homework1.Team.members
        */insert
    into
    team_member (team_id, members_id)
    values
    (?, ?)