Hibernate:
drop table if exists member cascade
    Hibernate:
drop table if exists team cascade
    Hibernate:
create table member (
                        id bigint generated by default as identity,
                        team_id bigint,
                        name varchar(50) not null,
                        primary key (id)
)
    Hibernate:
create table team (
                      id bigint generated by default as identity,
                      name varchar(255),
                      primary key (id)
)
    Hibernate:
alter table if exists member
    add constraint FKcjte2jn9pvo9ud2hyfgwcja0k
    foreign key (team_id)
    references team
    Hibernate:
    /* insert
    for
        chapter6.homework1.Team
        */insert
    into
    team (name, id)
    values
    (?, default)
    Hibernate:
    /* insert
    for
        chapter6.homework1.Member
        */insert
    into
    member (name, id)
    values
    (?, default)
    Hibernate:
    /* insert
    for
        chapter6.homework1.Member
        */insert
    into
    member (name, id)
    values
    (?, default)
    Hibernate:
update
    member
set
    team_id=?
where
    id=?
    Hibernate:
update
    member
set
    team_id=?
where
    id=?

    BUILD SUCCESSFUL in 961ms